PUT http://localhost:3001/api/persons/6304e9f76a5b8c8d256a96d7 HTTP/1.1
content-type: application/json

{
    "name": "Green Bubbles",
    "number": "024-124-923"
}

###

GET http://localhost:3001/api/persons/6303736be7c2dfcff1cdadcc

###

DELETE http://localhost:3001/api/persons/6304ef3ea7a7318b1bfb9e77
